In [8]:
import regTrees
import numpy as np

In [9]:
testMat = np.mat(np.eye(4))
print testMat

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [10]:
mat0,mat1 = regTrees.binSplitDataSet(testMat,1,0.5)
print mat0
print mat1

[[ 0.  1.  0.  0.]]
[[ 1.  0.  0.  0.]]


In [43]:
reload(regTrees)
myDat = regTrees.loadDataSet('ex00.txt')
myMat = np.mat(myDat)
regTrees.createTree(myMat.T)

0 0.036098
<class 'numpy.matrixlib.defmatrix.matrix'> (1L, 200L)
mat0 (1L, 200L)
<class 'numpy.matrixlib.defmatrix.matrix'> (1L, 200L)
mat1 (1L, 200L)
0 0.155096
<class 'numpy.matrixlib.defmatrix.matrix'> (0L, 200L)
mat0 (0L, 200L)
<class 'numpy.matrixlib.defmatrix.matrix'> (2L, 200L)
mat1 (1L, 200L)
1 1.077553
<class 'numpy.matrixlib.defmatrix.matrix'> (0L, 200L)
mat0 (0L, 200L)
<class 'numpy.matrixlib.defmatrix.matrix'> (2L, 200L)
mat1 (1L, 200L)
1 0.993349
<class 'numpy.matrixlib.defmatrix.matrix'> (1L, 200L)
mat0 (1L, 200L)
<class 'numpy.matrixlib.defmatrix.matrix'> (1L, 200L)
mat1 (1L, 200L)
2 0.530897
<class 'numpy.matrixlib.defmatrix.matrix'> (1L, 200L)
mat0 (1L, 200L)
<class 'numpy.matrixlib.defmatrix.matrix'> (1L, 200L)
mat1 (1L, 200L)
2 0.893462
<class 'numpy.matrixlib.defmatrix.matrix'> (0L, 200L)
mat0 (0L, 200L)
<class 'numpy.matrixlib.defmatrix.matrix'> (2L, 200L)
mat1 (1L, 200L)
3 0.564858
<class 'numpy.matrixlib.defmatrix.matrix'> (1L, 200L)
mat0 (1L, 200L)
<class 'numpy

0.1485205

In [44]:
print regTrees

<module 'regTrees' from 'regTrees.py'>


In [4]:
import os 
execfile('treeExplore.py')

0 0.179389
mat0 (1L, 2L)
<class 'numpy.matrixlib.defmatrix.matrix'> (37L, 2L)
mat1 (1L, 2L)
0 0.194894
mat0 (1L, 2L)
<class 'numpy.matrixlib.defmatrix.matrix'> (43L, 2L)
mat1 (1L, 2L)
0 0.981951
mat0 (1L, 2L)
<class 'numpy.matrixlib.defmatrix.matrix'> (195L, 2L)
mat1 (1L, 2L)
0 0.47226
mat0 (1L, 2L)
<class 'numpy.matrixlib.defmatrix.matrix'> (107L, 2L)
mat1 (1L, 2L)
0 0.734653
mat0 (1L, 2L)
<class 'numpy.matrixlib.defmatrix.matrix'> (151L, 2L)
mat1 (1L, 2L)
0 0.133461
mat0 (1L, 2L)
<class 'numpy.matrixlib.defmatrix.matrix'> (26L, 2L)
mat1 (1L, 2L)
0 0.77984
mat0 (1L, 2L)
<class 'numpy.matrixlib.defmatrix.matrix'> (163L, 2L)
mat1 (1L, 2L)
0 0.947922
mat0 (1L, 2L)
<class 'numpy.matrixlib.defmatrix.matrix'> (189L, 2L)
mat1 (1L, 2L)
0 0.010729
mat0 (1L, 2L)
<class 'numpy.matrixlib.defmatrix.matrix'> (2L, 2L)
mat1 (1L, 2L)
0 0.515337
mat0 (1L, 2L)
<class 'numpy.matrixlib.defmatrix.matrix'> (116L, 2L)
mat1 (1L, 2L)
0 0.74771
mat0 (1L, 2L)
<class 'numpy.matrixlib.defmatrix.matrix'> (154L, 2L)

ValueError: Masked arrays must be 1-D